@echo off
echo Adding firewall rule for port 3000...
netsh advfirewall firewall add rule name="Cold Storage Server" dir=in action=allow protocol=TCP localport=3000
echo.
echo Done! Press any key to close...
pause >nul
